### ISSUE TITLE
Specify Package Requirements

### ISSUE THREAD

**Issue by danphenderson** [ShaliniAnandaPhD/ISBRT#1]
Add a pyproject.toml, or, at a minimum a requirements.txt to specify your Python requirements.

Cool project! By adding this feature, more people will be inclined to use it. It is currently frustrating to have to find the requirements throughout various locations in your README.md.

**Comment by ShaliniAnandaPhD** [comment]
Hi Dan,
Thank you for reaching out with feedback! I understand it can frustrating, so I've proceeded to add the requirements.txt. I have a few more commits to make and following that, I'll add the pyproject.tml.
